const express=require('express'),Database=require('better-sqlite3'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cookieParser=require('cookie-parser'),{v4:uuidv4}=require('uuid');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'fastexpress2025secure';
app.use(express.json());app.use(cookieParser());
const db=new Database('fx.db');
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,phone TEXT,password TEXT,role TEXT DEFAULT 'client',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS shipments(id TEXT PRIMARY KEY,tracking_number TEXT UNIQUE,sender_name TEXT,sender_address TEXT,sender_phone TEXT,receiver_name TEXT,receiver_address TEXT,receiver_phone TEXT,receiver_email TEXT,description TEXT,weight REAL DEFAULT 1,service_type TEXT DEFAULT 'standard',status TEXT DEFAULT 'pending',estimated_delivery TEXT,price REAL DEFAULT 0,notes TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS tracking_events(id TEXT PRIMARY KEY,shipment_id TEXT,status TEXT,location TEXT,description TEXT,timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,name TEXT,email TEXT,phone TEXT,subject TEXT,message TEXT,read INTEGER DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare('SELECT id FROM users WHERE email=?').get('admin@fastexpress.com')){db.prepare('INSERT INTO users(id,name,email,phone,password,role)VALUES(?,?,?,?,?,?)').run(uuidv4(),'Admin','admin@fastexpress.com','07059137221',bcrypt.hashSync('fastexpress2025',10),'admin');}
function auth(req,res,next){const t=req.cookies.token||req.headers.authorization?.replace('Bearer ','');if(!t)return res.status(401).json({error:'Unauthorized'});try{req.user=jwt.verify(t,SECRET);next();}catch{res.status(401).json({error:'Invalid token'});}}
function adm(req,res,next){auth(req,res,()=>{if(req.user.role!=='admin')return res.status(403).json({error:'Forbidden'});next();});}
app.post('/api/auth/register',(req,res)=>{const{name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Missing fields'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return res.status(409).json({error:'Email already registered'});const id=uuidv4();db.prepare('INSERT INTO users(id,name,email,phone,password)VALUES(?,?,?,?,?)').run(id,name,email,phone||'',bcrypt.hashSync(password,10));const token=jwt.sign({id,name,email,role:'client'},SECRET,{expiresIn:'7d'});res.cookie('token',token,{httpOnly:true,maxAge:604800000});res.json({success:true,user:{id,name,email,role:'client'},token});});
app.post('/api/auth/login',(req,res)=>{const{email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password,u.password))return res.status(401).json({error:'Invalid email or password'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'7d'});res.cookie('token',token,{httpOnly:true,maxAge:604800000});res.json({success:true,user:{id:u.id,name:u.name,email:u.email,role:u.role},token});});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('token');res.json({success:true});});
app.get('/api/track/:tn',(req,res)=>{const s=db.prepare('SELECT * FROM shipments WHERE tracking_number=?').get(req.params.tn.toUpperCase());if(!s)return res.status(404).json({error:'Tracking number not found'});const events=db.prepare('SELECT * FROM tracking_events WHERE shipment_id=? ORDER BY timestamp ASC').all(s.id);res.json({tracking_number:s.tracking_number,status:s.status,service_type:s.service_type,description:s.description,weight:s.weight,estimated_delivery:s.estimated_delivery,sender_city:s.sender_address,receiver_city:s.receiver_address,receiver_name:s.receiver_name,created_at:s.created_at,events});});
app.post('/api/contact',(req,res)=>{const{name,email,phone,subject,message}=req.body;if(!name||!email||!message)return res.status(400).json({error:'Missing fields'});db.prepare('INSERT INTO contacts(id,name,email,phone,subject,message)VALUES(?,?,?,?,?,?)').run(uuidv4(),name,email,phone||'',subject||'',message);res.json({success:true,message:"Message received!"});});
app.get('/api/admin/stats',adm,(req,res)=>{res.json({total:db.prepare('SELECT COUNT(*) as c FROM shipments').get().c,delivered:db.prepare("SELECT COUNT(*) as c FROM shipments WHERE status='delivered'").get().c,in_transit:db.prepare("SELECT COUNT(*) as c FROM shipments WHERE status IN('in_transit','out_for_delivery','collected','processing')").get().c,pending:db.prepare("SELECT COUNT(*) as c FROM shipments WHERE status='pending'").get().c,revenue:db.prepare('SELECT SUM(price) as s FROM shipments').get().s||0,unread_contacts:db.prepare('SELECT COUNT(*) as c FROM contacts WHERE read=0').get().c});});
app.get('/api/admin/shipments',adm,(req,res)=>res.json(db.prepare('SELECT * FROM shipments ORDER BY created_at DESC').all()));
app.post('/api/admin/shipments',adm,(req,res)=>{const{sender_name,sender_address,sender_phone,receiver_name,receiver_address,receiver_phone,receiver_email,description,weight,service_type,estimated_delivery,price,notes}=req.body;if(!sender_name||!receiver_name)return res.status(400).json({error:'Missing fields'});const id=uuidv4(),seq=String(db.prepare('SELECT COUNT(*) as c FROM shipments').get().c+1).padStart(6,'0'),tn='FX-'+new Date().getFullYear()+'-'+seq;db.prepare('INSERT INTO shipments(id,tracking_number,sender_name,sender_address,sender_phone,receiver_name,receiver_address,receiver_phone,receiver_email,description,weight,service_type,status,estimated_delivery,price,notes)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,"pending",?,?,?)').run(id,tn,sender_name,sender_address||'',sender_phone||'',receiver_name,receiver_address||'',receiver_phone||'',receiver_email||'',description||'',parseFloat(weight)||1,service_type||'standard',estimated_delivery||'',parseFloat(price)||0,notes||'');db.prepare('INSERT INTO tracking_events(id,shipment_id,status,location,description)VALUES(?,?,?,?,?)').run(uuidv4(),id,'pending',sender_address||'Origin','Shipment created');res.json({success:true,tracking_number:tn,id});});
app.put('/api/admin/shipments/:id/status',adm,(req,res)=>{const{status,location,description}=req.body;db.prepare('UPDATE shipments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,req.params.id);db.prepare('INSERT INTO tracking_events(id,shipment_id,status,location,description)VALUES(?,?,?,?,?)').run(uuidv4(),req.params.id,status,location||'Fast Express Hub',description||'Status updated');res.json({success:true});});
app.delete('/api/admin/shipments/:id',adm,(req,res)=>{db.prepare('DELETE FROM tracking_events WHERE shipment_id=?').run(req.params.id);db.prepare('DELETE FROM shipments WHERE id=?').run(req.params.id);res.json({success:true});});
app.get('/api/admin/contacts',adm,(req,res)=>{const c=db.prepare('SELECT * FROM contacts ORDER BY created_at DESC').all();db.prepare('UPDATE contacts SET read=1').run();res.json(c);});
app.get('/api/admin/users',adm,(req,res)=>res.json(db.prepare('SELECT id,name,email,phone,role,created_at FROM users ORDER BY created_at DESC').all()));
app.get('*',(req,res)=>res.sendFile(__dirname+'/public/index.html'));
app.listen(PORT,()=>console.log('Fast Express on port '+PORT));
